version: '3.2'

networks:
  poll:
    driver: bridge

services:
  poll_nginx:
    container_name: poll_nginx
    working_dir: /application1
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../:/application1
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    links:
      - 'poll_phpfpm'
    networks:
      - poll

  poll_phpfpm:
    container_name: poll_phpfpm
    build:
      context: ../
      dockerfile: docker/php_fpm/Dockerfile
    working_dir: /application1
    restart: unless-stopped
    volumes:
      - ../:/application1
      - ../docker/php_fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - poll

  poll_pgsql:
    container_name: poll_pgsql
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - poll